vectornav:
  ros__parameters:
    autostart: true
    port: /dev/vectornav
    baud: 921600
    reconnect_ms: 500
    AsyncDataOutputType: 0
    AsyncDataOutputFrequency: 50
    syncInMode: 3
    syncInEdge: 0
    syncInSkipFactor: 0
    syncOutMode: 0
    syncOutPolarity: 0
    syncOutSkipFactor: 0
    syncOutPulseWidth_ns: 100000000
    serialCount: 0
    serialStatus: 0
    spiCount: 0
    spiStatus: 0
    serialChecksum: 1
    spiChecksum: 0
    errorMode: 1
    BO1:
      asyncMode: 1
      rateDivisor: 16
      commonField: 7675
      timeField: 0
      imuField: 0
      gpsField: 0
      attitudeField: 0
      insField: 0
      gps2Field: 0
    BO2:
      asyncMode: 3
      rateDivisor: 16
      commonField: 0
      timeField: 0
      imuField: 0
      gpsField: 0
      attitudeField: 328
      insField: 1545
      gps2Field: 0
    BO3:
      asyncMode: 3
      rateDivisor: 160
      commonField: 0
      timeField: 0
      imuField: 0
      gpsField: 1593
      attitudeField: 0
      insField: 0
      gps2Field: 0
    frame_id: imu_link
    adjust_ros_timestamp: false
    gpsAntennaOffset:
      - 0.004
      - 0.0
      - -0.205
vn_sensor_msgs:
  ros__parameters:
    dynamic_uncertanity: true
    gravity_removed_accel: true
    orientation_covariance:
      - 0.00121847072
      - 0.00007615442
      - 0.00007615442
    position_covariance:
      - 1.0
      - 1.0
      - 2.25
    velocity_covariance:
      - 0.0025
      - 0.0025
      - 0.0025
    angular_velocity_covariance:
      - 0.01
      - 0.01
      - 0.01
    linear_acceleration_covariance:
      - 0.01
      - 0.01
      - 0.01
    magnetic_field_covariance:
      - 0.01
      - 0.01
      - 0.01
